name: Test

on:
  pull_request:
    branches: ["develop"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout And Cache
      uses: ./.github/actions/checkout-and-cache
    - name: Build test
      run: cargo build --release --verbose
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout And Cache
      uses: ./.github/actions/checkout-and-cache
    - name: Test
      run: cargo test --verbose

  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout And Cache
      uses: ./.github/actions/checkout-and-cache
    - name: E2E
      run: bash e2e.sh

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout And Cache
      uses: ./.github/actions/checkout-and-cache
    - name: Lint with Clippy
      run: cargo clippy --all-targets --all-features
    
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout And Cache
      uses: ./.github/actions/checkout-and-cache
    - name: Format with Rustfmt
      run: cargo fmt --all --check
